networks:
  ai-for-php-developers:
    driver: bridge

services:
  # -------------------------------------------------------
  # APPLICATION
  # -------------------------------------------------------
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8088:8088"
    command: php -S 0.0.0.0:8088 -t public
    networks:
      - ai-for-php-developers

